Repository gardener/cluster-api-provider-gardener, pull requests merged in 2025-07, with the labels that each got.

#9 Add make target to generate Gardener kcp-schemas
  Makefile
  hack/generate-schemas.sh
  schemas/gardener/apiexport-controlplane.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-gardenershootclusters.infrastructure.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-gardenershootcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-gardenerworkerpools.infrastructure.cluster.x-k8s.io.yaml
Labels: kind/enhancement, lgtm, approved, area/dev-productivity, cla: yes, size/XXL

#6 Update g/g from `v1.118.1` to `v1.121.2`.
  .github/renovate.json5
  api/infrastructure/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_gardenershootcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gardenerworkerpools.yaml
  go.mod
  go.sum
  schemas/gardener/apiresourceschema-gardenershootcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-gardenerworkerpools.infrastructure.cluster.x-k8s.io.yaml
Labels: kind/enhancement, lgtm, approved, cla: yes, size/XL

#15 Enable Renovate to update dependencies referenced in Makefile
  Makefile
Labels: kind/enhancement, lgtm, approved, area/dev-productivity, cla: yes, size/S

#23 Adapt generate-schemas Make target to also generate CAPI schemas
  .github/renovate.json5
  Makefile
  go.mod
  go.sum
  hack/generate-schemas.sh
  schemas/gardener/apiexport-controlplane.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-clusters.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-machinepools.cluster.x-k8s.io.yaml
Labels: kind/enhancement, lgtm, approved, area/dev-productivity, cla: yes, size/XXL

#25 Align `GardenerWorkerPool` behavior to `MachinePool` contract
  config/rbac/role.yaml
  internal/controller/infrastructure/gardenerworkerpool_controller.go
Labels: kind/enhancement, area/quality, lgtm, size/M, approved, cla: yes

#30 Update module sigs.k8s.io/cluster-api to v1.10.3
  .github/renovate.json5
  Makefile
  config/crd/bases/controlplane.cluster.x-k8s.io_gardenershootcontrolplanes.yaml
  go.mod
  go.sum
  schemas/gardener/apiresourceschema-clusters.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-gardenershootcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  schemas/gardener/apiresourceschema-machinepools.cluster.x-k8s.io.yaml
Labels: kind/enhancement, lgtm, approved, cla: yes, size/L

#35 Migrate to g/g's `$(SETUP_ENVTEST)` target and fix integration test flake
  Makefile
  internal/controller/controlplane/gardenershootcontrolplane_controller_test.go
  internal/controller/controlplane/suite_test.go
  internal/controller/infrastructure/gardenerworkerpool_controller_test.go
  internal/controller/infrastructure/suite_test.go
  internal/webhook/controlplane/v1alpha1/webhook_suite_test.go
  internal/webhook/infrastructure/v1alpha1/webhook_suite_test.go
Labels: lgtm, size/M, approved, cla: yes, area/robustness, kind/flake, kind/cleanup, area/testing

#36 Add `kind-kcp` e2e test
  Makefile
  docs/kcp/getting-started-locally.md
  test/e2e/kind-kcp/e2e_suite_test.go
  test/e2e/kind-kcp/e2e_test.go
  test/e2e/kind/e2e_suite_test.go
  test/e2e/kind/e2e_test.go
  test/utils/kcp.go
  test/utils/utils.go
Labels: kind/enhancement, area/quality, lgtm, approved, area/dev-productivity, cla: yes, area/robustness, kind/test, area/testing, size/XL

#39 Add experimental warning to README
  README.md
Labels: area/documentation, kind/enhancement, lgtm, approved, cla: yes, size/XS

#41 Fix renovate config exclusions
  .github/renovate.json5
  docs/kcp/getting-started-locally.md
Labels: lgtm, approved, kind/impediment, cla: yes, size/XS, area/testing

#42 Fix golang version detection
  Dockerfile
  Makefile
  hack/kind-gardener.sh
Labels: kind/bug, lgtm, approved, area/delivery, cla: yes, size/S

#43 Fix golang version resolution
  Dockerfile
Labels: kind/bug, lgtm, approved, area/delivery, cla: yes, size/XS

#45 Add missing packages to the `prepare_release` script
  .ci/hack/prepare_release
Labels: kind/bug, lgtm, approved, area/delivery, cla: yes, size/S

#46 Migrate from Concourse to GitHub Actions
  .ci/component_descriptor
  .ci/hack/component_descriptor
  .ci/hack/doc.go
  .ci/hack/prepare_release
  .ci/pipeline_definitions
  .ci/prepare_release
  .ci/verify
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  Makefile
Labels: kind/task, kind/technical-debt, lgtm, approved, area/delivery, cla: yes, size/L
